### ISSUE TITLE
Does not seem to work with VSCode 1.53

### ISSUE THREAD

**Issue by coxackie** [Astrapios/vscode_python_repl#1]
Hey, thanks for this extension. I cannot seem to make it work at v1.53. Does it work OK for you? I "activate" python REPL (I have ipython installed), I get the notification that Python REPL activated, but the terminal is not launching anything. When I send text, nothing happens...

**Comment by Astrapios** [comment]
Thanks for using it! It is caused by a missing `pythonTerminal._queuedRequests` property that is depreciated in VSCode v.1.53. I pushed an update, so It should work as intended now.
